from bson import ObjectId
from db import users_collection



class User:
    def __init__(
        self,
        email,
        full_name,
        password,
        username=None,
        profile =None,
        preferences=None,
        _id=None,
    ):
        self._id = ObjectId(_id) if _id else None
        self.full_name = full_name
        self.email = email
        self.username = username
        self.password = password
        self.profile = profile if profile else {"description": "", "links": []}
        self.preferences = preferences

    def to_dict(self):
        """Convert User object to dictionary"""
        return {
            "_id": self._id,
            "full_name": self.full_name,
            "email": self.email,
            "username": self.username,
            "password": self.password,
            "profile": self.profile,
            "preferences": self.preferences,
        }

    def to_json(self):
        """Convert User object to JSON-serializable dictionary"""
        return {
            "_id": str(self._id) if self._id else None,
            "full_name": self.full_name,
            "email": self.email,
            "username": self.username,
            "profile": self.profile,
            "preferences": self.preferences,
        }

    def create(self):
        """Create a new user"""
        try:
            user_data = self.to_dict()
            # Remove _id for creation, as it's generated by MongoDB
            if user_data.get("_id") is None:
                del user_data["_id"]
            
            result = users_collection.insert_one(user_data)
            self._id = result.inserted_id
            return str(result.inserted_id)
        except Exception as e:
            raise Exception(f"Failed to create user: {str(e)}")

    def update(self, updates):
        """Update an existing user"""
        if not self._id:
            raise ValueError("Cannot update user without _id")
        
        try:
            
            update_data = {k: v for k, v in updates.items() if v is not None}
            
            # Update object attributes
            for key, value in update_data.items():
                if hasattr(self, key):
                    setattr(self, key, value)
            
            result = users_collection.update_one({"_id": self._id}, {"$set": update_data})
            return result.modified_count > 0
        except Exception as e:
            raise Exception(f"Failed to update user: {str(e)}")
    
    def delete(self):
        """Delete the user"""
        if not self._id:
            raise ValueError("Cannot delete user without _id")
        
        try:
            
            result = users_collection.delete_one({"_id": self._id})
            return result.deleted_count > 0
        except Exception as e:
            raise Exception(f"Failed to delete user: {str(e)}")
    
    @staticmethod
    def get_by_email(email):
        user = users_collection.find_one(filter={"email":email})
        if user:
            return User(**user)
        return None

    @staticmethod
    def get_by_id(user_id):
        user = users_collection.find_one(filter={"_id":ObjectId(user_id)})
        if user:
            return User(**user)
        return None
